# swagger.yaml
openapi: 3.0.0
info: 
  description: An R api to provide data for visualization of insights
  title: Ship Study Api
  version: 1.0.0
servers:
  - description: Dev server
    url: http://localhost:3000
paths:
  /getFeatureImportance:
    get: 
      summary: returns feature importance co-ordinates
      description: endpoint to fetch feature importance
      responses:
        '200': 
          description: A JSON Array with 3 elements. First array consists of x-coords, Second one consists of y-coords, Third one consists of label descriptions
          content: 
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: array
                      items:
                        type: number
                        format: float
                    - type: array
                      items:
                        type: number
                        format: float
                    - type: array
                      items:
                        type: string
        '404':
          description: Feature Importance was not found
        default:
          description: Unexpected Error
  /getIceCoords:
    post:
      summary: returns co-ordinates for plotting ICE for a specific feature requested
      description: endpoint to fetch ICE co-ords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feature_name: 
                  type: string
                  description: feature to be explored using ICE plot
                  example: frac_class_0_in_neighborhood_s2
              required:
                - feature_name
      responses: 
        '200':
          description: A JSON Array with 2 elements. First is an array of x-co-ords. Second is the array of y-coords
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Feature was not found
        default:
          description: Unexpected Error
